package io.github.vinicius.sentinel.payments;

public enum PaymentIntentErrorCode {
	INVALID_TRANSITION,
	INVALID_AMOUNT,
	CURRENCY_MISMATCH,
	CAPTURE_EXCEEDS_AUTHORIZED_AMOUNT,
	REFUND_EXCEEDS_CAPTURED_AMOUNT,
	NON_MONOTONIC_TIMESTAMP,
	INVALID_AGGREGATE_STATE
}
