package io.github.vinicius.sentinel;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;
import org.springframework.context.annotation.Import;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import tools.jackson.databind.MapperFeature;
import tools.jackson.databind.ObjectMapper;
import tools.jackson.databind.json.JsonMapper;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.fail;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * CI's "OpenAPI drift is visible and intentionally reviewed" gate. The committed baseline is regenerated by
 * deleting it and rerunning this test locally: a missing baseline makes the test write the current spec and fail
 * with instructions instead of silently passing, so a contract change can never slip in as a passing CI run with
 * no reviewable diff.
 */
@SpringBootTest(properties = {
	"sentinel.merchant.directory[0].id=11111111-1111-1111-1111-111111111111",
	"sentinel.merchant.directory[0].api-key-id=sentinel-dev-merchant",
	"sentinel.merchant.directory[0].api-key-secret=sentinel-dev-secret"
})
@AutoConfigureMockMvc
@Import(TestcontainersConfiguration.class)
class OpenApiDriftIntegrationTests {

	private static final Path BASELINE = Path.of("docs/openapi/openapi.json");

	@Autowired
	private MockMvc mockMvc;

	@Test
	void theServedOpenApiContractMatchesTheCommittedBaseline() throws Exception {
		String current = normalize(fetchCurrentSpec());

		if (Files.notExists(BASELINE)) {
			Files.createDirectories(BASELINE.getParent());
			Files.writeString(BASELINE, current, StandardOpenOption.CREATE_NEW);
			fail(
				"No committed OpenAPI baseline existed, so one was generated at " + BASELINE + ". "
					+ "Review it, commit it, and rerun this test."
			);
		}

		String baseline = Files.readString(BASELINE);
		assertThat(current)
			.as(
				"The served OpenAPI contract no longer matches %s. If this change is intentional, delete the "
					+ "file, rerun this test to regenerate it, review the diff, and commit it alongside the API change.",
				BASELINE
			)
			.isEqualTo(baseline);
	}

	private String fetchCurrentSpec() throws Exception {
		MvcResult result = mockMvc.perform(get("/v3/api-docs"))
			.andExpect(status().isOk())
			.andReturn();
		return result.getResponse().getContentAsString();
	}

	private static String normalize(String rawJson) throws IOException {
		ObjectMapper mapper = JsonMapper.builder()
			.enable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
			.build();
		Object tree = mapper.readValue(rawJson, Object.class);
		return mapper.writerWithDefaultPrettyPrinter().writeValueAsString(tree) + "\n";
	}
}
